"""Regenerate the blueprint's declaration table and module graph from the Lean sources."""
import re, sys, json
from pathlib import Path
WS = Path.home()/"do/Lea/apps/lea-standalone/prover/workspace/proofs/DeadDirections"
P = Path("/Users/tsh/do/tau/papers/geometric-singularity-detection")
BP = P/"proofs/BLUEPRINT.md"
MODS = P/"proofs/blueprint/modules.mmd"
RES = P/"proofs/blueprint/results.mmd"
DECL = re.compile(r'^\s*(?:@\[[^\]]*\]\s*)?(?:private\s+|protected\s+)?(?:noncomputable\s+)?(theorem|lemma|def|abbrev|structure|class|instance|inductive)\s+([^\s:(\{\[⦃]+)')
decls = {}   # name -> (file, line)
imports = {} # module -> [imported modules]
for f in sorted(WS.glob("*.lean")):
    mod = f.stem
    stack = []
    imports[mod] = []
    for ln, line in enumerate(f.read_text().splitlines(), 1):
        m = re.match(r'^import DeadDirections\.(\w+)', line)
        if m: imports[mod].append(m.group(1)); continue
        m = re.match(r'^namespace\s+(\S+)', line)
        if m: stack.append(('ns', m.group(1))); continue
        m = re.match(r'^section\s*(\S*)', line)
        if m: stack.append(('sec', m.group(1))); continue
        m = re.match(r'^end\s*(\S*)\s*$', line)
        if m:
            if stack: stack.pop()
            continue
        m = DECL.match(line)
        if m:
            name = m.group(2)
            ns = [n for k, n in stack if k == 'ns' and n != 'DeadDirections']
            full = '.'.join(ns + [name]) if not name.startswith('_root_.') else name[7:]
            decls.setdefault(full, (f"DeadDirections/{f.name}", ln))
            bare = name.split('.')[-1]
            decls.setdefault(bare, (f"DeadDirections/{f.name}", ln)) if bare != full else None
# names cited in BLUEPRINT.md outside the table
text = BP.read_text()
head, sep, table = text.partition("## Declaration verification")
cited = sorted(set(re.findall(r'`([A-Za-z_][\w.\'₀-₉]*)`', head)))
rows, missing = [], []
for c in cited:
    if c in decls:
        rows.append((c, *decls[c]))
    else:
        missing.append(c)
intro = table.split("| Declaration | File | Line |")[0]
new_table = "## Declaration verification" + intro + "| Declaration | File | Line |\n|---|---|---|\n" + "\n".join(f"| `{n}` | `{f}` | {l} |" for n, f, l in rows) + "\n"
BP.write_text(head + new_table)
print("table rows", len(rows), "uncited/unmatched tokens", len(missing))
print("unmatched:", [m for m in missing if '_' in m or '.' in m][:60])
# modules.mmd
old = MODS.read_text().splitlines()
groups = {}; cur = None; order = []
for line in old:
    m = re.match(r'\s*subgraph (\w+)\["([^"]+)"\]', line)
    if m: cur = (m.group(1), m.group(2)); order.append(cur); groups[cur] = []; continue
    if line.strip() == 'end': cur = None; continue
    m = re.match(r'\s+(\w+)\["\1"\]', line)
    if m and cur: groups[cur].append(m.group(1))
placed = {x for g in groups.values() for x in g}
vol = [g for g in order if g[0] == 'Volume_and_RLCT'][0]
for mod in sorted(imports):
    if mod not in placed: groups[vol].append(mod); placed.add(mod)
edges = [(a, b) for b in sorted(imports) for a in imports[b]]
tail = [l for l in old if l.startswith('  classDef') or l.startswith('  class ')]
out = ["%% Module import graph of the DeadDirections Lean package.",
       f"%% {len(imports)} modules, {len(edges)} intra-package import edges.",
       "%% An arrow from A to B means B contains the line `import DeadDirections.A`.",
       "%% Generated by reading the import lines of proofs/DeadDirections/*.lean.",
       "graph LR"]
for key, label in order:
    out.append(f'  subgraph {key}["{label}"]')
    out += [f'    {m}["{m}"]' for m in groups[(key, label)]]
    out.append("  end")
out += [f"  {a} --> {b}" for a, b in edges]
out.append("")
out += tail
MODS.write_text("\n".join(out) + "\n")
print("modules.mmd:", len(imports), "modules,", len(edges), "edges")
# results.mmd
r = RES.read_text()
r = r.replace("  class thm_nu_universality,prop_determinantal_resolution out;\n", "")
r = re.sub(r"(  class [^\n]*cor_ddcadam_quotient_rate) partial;", r"\1,thm_nu_universality,prop_determinantal_resolution partial;", r)
if "prop_determinantal_resolution --> thm_multi_component_rates" not in r:
    r = r.replace("  thm_multi_component_rates --> prop_volume_multi\n", "  prop_determinantal_resolution --> thm_multi_component_rates\n  thm_multi_component_rates --> prop_volume_multi\n")
RES.write_text(r)
print("results.mmd: out class removed:", "out;" not in r.split("classDef out")[1] if "classDef out" in r else "n/a")
print([l for l in r.splitlines() if l.startswith('%%') and re.search(r'\d', l)])
